---
#
# Add Public SSH Keys to Authorized Keys file
#

# Edit ~/.ssh/authorized_keys to include our public keys

  - name: Add SSH keys to ~/.ssh/authorized_keys
    authorized_key:
      user: ubuntu
      state: present
      key: "{{ lookup('file', '/Users/mgulati/Documents/vscode-projects/stackoverflow-clone/ansible/keys/authorized_keys') }}"