---
# 
# Installing and Configuring Cassandra 2.2
#

    - name: Add Apache Cassandra Repository Keys
      apt_key:
        url: https://www.apache.org/dist/cassandra/KEYS
        state: present

    - name: Add Apache Cassandra Repository
      apt_repository:
        repo: deb http://www.apache.org/dist/cassandra/debian 22x main
        filename: cassandra
        state: present

    - name: Update APT Cache and Install Cassandra 2.2
      apt:
        name: cassandra
        update_cache: yes
