---
#
# Playbook to install the ELK stack
#
- hosts: elk
  remote_user: ubuntu
  become: yes
  become_user: root
  vars:
    nginx_path: /etc/nginx
    nginx_sites: "{{ nginx_path }}/sites-available"
  roles:
  - { role: ssh }
  - { role: nginx }
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }

  tasks:
    - name: Installing Python3 and pip3
      apt:
        name: python3-pip
        update_cache: yes

    - name: Installing passlib as dependency for module 'htpasswd'
      pip:
        name: passlib

    - name: Setup basic authorization in Nginx
      htpasswd:
        path: /etc/nginx/htpasswd.users
        name: admin
        password: ferdman123
    
    - name: Create and setup server block to proxy Kibana and Elasticsearch from template
      template:
        src: templates/elk.j2
        dest: "{{ nginx_sites }}/elk"
    
    - name: Link sites-available to sites-enabled.
      shell: ln -s /etc/nginx/sites-available/elk /etc/nginx/sites-enabled/elk
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted