---
#
# Playbook to setup the user service.
#
- hosts: services
  serial: 1
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  vars:
    GIT_USERNAME: devhid
    GIT_TOKEN: "{{ lookup('file', '/Users/mgulati/Documents/vscode-projects/stackoverflow-clone/ansible/keys/git_ansible') }}"

  tasks:
    - name: Append "-verification" if inventory host is "email", otherwise append "-service"
      set_fact:
        full_hostname: "{% if inventory_hostname == 'email' %}email-verification-service{% else %}{{ inventory_hostname }}-service{% endif %}"

    - name: Pull changes from Git
      become_user: ubuntu
      git:
        repo: http://{{ GIT_USERNAME }}:{{ GIT_TOKEN }}@github.com/devhid/stackoverflow-clone.git
        dest: /home/ubuntu/stackoverflow-clone
        force: yes
    
    - name: Install dependencies for {{ full_hostname }}
      become_user: ubuntu
      shell: cd stackoverflow-clone/services/{{ full_hostname }} && npm install
    
    - name: Restart {{ full_hostname }} with pm2
      become_user: ubuntu
      shell: cd stackoverflow-clone/services/{{ full_hostname }} && pm2 restart index.js --name {{ full_hostname }} 
