---
#
# Playbook to setup the router that will act as an API gateway.
#
- hosts: router
  remote_user: ubuntu
  become: yes
  become_user: root
  vars:
    GIT_USERNAME: devhid
    GIT_TOKEN: "{{ lookup('file', '/Users/mgulati/Documents/vscode-projects/stackoverflow-clone/ansible/keys/git_ansible') }}"
  roles:
  - { role: ssh }
  - { role: nginx }
  - { role: nodejs }
  - { role: rabbitmq }

  tasks:
    - name: Clone stackoverflow-clone repository from Git
      become_user: ubuntu
      git:
        repo: http://{{ GIT_USERNAME }}:{{ GIT_TOKEN }}@github.com/devhid/stackoverflow-clone.git
        dest: /home/ubuntu/stackoverflow-clone
    
    - name: Install dependencies for router
      become_user: ubuntu
      shell: cd stackoverflow-clone/rabbitmq/routing && npm install
    
    - name: Start router with pm2
      become_user: ubuntu
      shell: cd stackoverflow-clone/rabbitmq/routing && pm2 start index.js --name router
